{% set name = "mdformat" %}
{% set version = "0.7.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdformat-{{ version }}.tar.gz
  sha256: 0e44b6402a7f80e9a707ef6886e63ea87bea7203627466dbe3898f9d16d51e1b

build:
  number: 0
  noarch: python
  entry_points:
    - mdformat = mdformat.__main__:run
  script: {{ PYTHON }} -m pip install . -vv

# Check [tool.poetry.dependencies] in
#   https://github.com/executablebooks/mdformat/blob/master/pyproject.toml
requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core
  run:
    - python >=3.7
    - tomli >=1.1.0
    - markdown-it-py >=1.0.0b2,<2.0.0
    - importlib-metadata >=3.6.0
    - typing-extensions >=3.7.4

test:
  imports:
    - mdformat
    - mdformat.codepoints
  commands:
    - pip check
    - mdformat --help
  requires:
    - pip

about:
  home: https://github.com/executablebooks/mdformat
  summary: CommonMark compliant Markdown formatter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
