{% set name = "mdformat" %}
{% set version = "0.7.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdformat-{{ version }}.tar.gz
  sha256: f20300ecb8ddbb610f8ca99a50dc1a1a6cfb7465c6a6055f9c21f113fd9fe3c2

build:
  number: 0
  noarch: python
  entry_points:
    - mdformat = mdformat.__main__:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.1
    - poetry-core
  run:
    - importlib-metadata >=3.6.0
    - markdown-it-py >=1.0.0b2,<2.0.0
    - python >=3.6.1
    - typing-extensions >=3.7.4

test:
  imports:
    - mdformat
    - mdformat.codepoints
  commands:
    - pip check
    - mdformat --help
  requires:
    - pip

about:
  home: https://github.com/executablebooks/mdformat
  summary: CommonMark compliant Markdown formatter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
